project_name: gfetch

release:
  prerelease: auto
  draft: false
  name_template: "gfetch v{{ .Version }}"

builds:
  - id: linux
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    binary: bin/gfetch
    main: cmd/gfetch/main.go
    env:
      - CGO_ENABLED=0

  - id: macos
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: bin/gfetch
    main: cmd/gfetch/main.go
    env:
      - CGO_ENABLED=0

archives:
  - id: linux_archive
    builds:
      - linux
    format: tar.gz
    files:
      - README.md
      - LICENSE

  - id: macos_archive
    builds:
      - macos
    format: zip
    files:
      - README.md
      - LICENSE
